// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWBZClo5thDjOhdOwlPRSAMNE4j4yjjU',
    appId: '1:824833644826:android:6c33334e3b062ac11974a3',
    messagingSenderId: '824833644826',
    projectId: 'plexiform-being-384211',
    storageBucket: 'plexiform-being-384211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbK-aGRKZms6_z48M3D6JyMgqwb_0QmkM',
    appId: '1:824833644826:ios:332e244eea6175bf1974a3',
    messagingSenderId: '824833644826',
    projectId: 'plexiform-being-384211',
    storageBucket: 'plexiform-being-384211.appspot.com',
    androidClientId: '824833644826-6qpikgd273a88q6gq5a8pq68psr5tikj.apps.googleusercontent.com',
    iosClientId: '824833644826-cbnjj3mjabov6tgjm6b7i587lq87s6b7.apps.googleusercontent.com',
    iosBundleId: 'ets.noeli.xMoneyManager',
  );
}
